[node]
data_dir = "./test_data"
validator = true
name = "adic-node-1"

[consensus]
p = 3
d = 3
rho = [2, 2, 1]
q = 3
k = 20
depth_star = 12
delta = 5
r_sum_min = 4.0
r_min = 1.0
deposit = 1.0
lambda = 1.0
beta = 0.5
mu = 1.0
gamma = 0.9

[storage]
backend = "rocksdb"
cache_size = 10000
snapshot_interval = 3600
max_snapshots = 10

[api]
enabled = true
host = "0.0.0.0"
port = 18081
max_connections = 100

[network]
enabled = true
p2p_port = 19001
quic_port = 9001
bootstrap_peers = []
dns_seeds = ["_seeds.adicl1.com"]
max_peers = 50
use_production_tls = false

[logging]
level = "info"
format = "pretty"  # Options: pretty, json, compact
use_emojis = true
show_fields_at = "debug"  # Show structured fields at: always, debug, trace, never
show_boot_banner = true
show_emoji_legend = true
# file_output = "./logs/adic.log"  # Uncomment to enable file logging
file_rotation_size_mb = 100

# Module-specific log levels (optional)
# [logging.module_filters]
# adic_network = "debug"
# adic_consensus = "info"