# ADIC Testnet Configuration
# This configuration connects to the ADIC testnet using DNS seed discovery

[node]
name = "testnet-validator"
data_dir = "./data/testnet"
validator = true
keypair_path = "./data/testnet/keypair.json"
bootstrap = false  # Set to true only for bootstrap nodes

[storage]
backend = "rocksdb"
cache_size = 134217728  # 128 MB
snapshot_interval = 1000
max_snapshots = 10

[consensus]
# Testnet parameters (same as mainnet for now)
p = 3
d = 3
k = 20
q = 3
rho = [2, 2, 1]
r_min = 0.5
r_sum_min = 2.0
depth_star = 12
delta = 5
beta = 1.0
gamma = 0.9
deposit = 0.1  # Test ADIC deposit amount
lambda = 1.0
mu = 1.0

[api]
enabled = true
host = "127.0.0.1"
port = 8080
max_connections = 100

[network]
enabled = true
p2p_port = 9000
quic_port = 9001
# Bootstrap peers will be discovered via DNS
bootstrap_peers = []
# DNS seed domains for automatic peer discovery
dns_seeds = ["_seeds.adicl1.com"]
max_peers = 50
use_production_tls = false  # Using self-signed certs for testnet
auto_update = true  # Enable automatic updates for testnet
ca_cert_path = ""
node_cert_path = ""
node_key_path = ""

# Economics and finality sections are not needed in node config

[logging]
level = "info"
format = "pretty"  # Options: pretty, json, compact
use_emojis = true
show_fields_at = "debug"
file_rotation_size_mb = 100
show_boot_banner = true
show_emoji_legend = true

[genesis]
deposit_amount = 0.1
timestamp = "2025-01-01T00:00:00Z"
chain_id = "adic-testnet"
genesis_identities = ["g0", "g1", "g2", "g3"]

# Test genesis allocations (smaller amounts for testnet)
allocations = [
    ["0100000000000000000000000000000000000000000000000000000000000000", 10_000],      # Treasury
    ["c1403f4763367340178077be2ab3144af2b9065901232335f960a9910bb9ab1b", 1_000],       # node-1
    ["2f89601b32149388d38652ac432307bf183eb97de87b5599cb76d256fd7a7f89", 1_000],       # node-2
    ["98831caf9b0861ec6eba3072275efc0de1557062043d317ba5f218361e028441", 1_000],       # node-3
    ["52ba18a771da5f8ebfb7e0eb88a229b748637c8041e0ddf06271b0511e67a5d4", 10_000],      # faucet
]

[genesis.parameters]
p = 3
d = 3
rho = [2, 2, 1]
q = 3
k = 20
depth_star = 12
homology_window = 5
alpha = 1.0
beta = 1.0